{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE LambdaCase #-}
-- | §18 Generation: the domain as native source, three times from one walk.
--
-- @arkc gen@ turns a verified module into ordinary Rust, Swift or Kotlin
-- over the library GENERATED.md names. There is one emitter; a 'Target'
-- decides spelling and nothing else. That is how the three outputs stay
-- alike: every construct of the IR is one function here with one branch
-- per target, so a body reads the same in all three down to the order of
-- its statements, and a runtime that follows the contract runs it as
-- 'Ark.Eval' says.
--
-- Generated code is dynamic — it computes over @Value@ and calls @Ops@,
-- @Std@ and the store — because sameness of meaning is the requirement
-- and a typed surface can be laid over it later without touching it. What
-- an app sees typed is the call surface at the end of the file.
module Ark.Gen
  ( Target (..)
  , generate
  , restrict
  , targetFileName
  ) where

import qualified Data.ByteString as B
import Data.Char (isAlphaNum, isUpper, ord, toLower, toUpper)
import qualified Data.Map.Strict as M
import Data.Text (Text)
import qualified Data.Text as T
import Numeric (showHex)

import Ark.Canon (encode)
import Ark.Encode (calls, toValue)
import Ark.Hash (closure, functionHash, moduleHash)
import Ark.IR
import Ark.Schema
import Ark.Value

data Target = Rust | Swift | Kotlin
  deriving (Eq, Show)

-- | The file a module's code goes in, by target.
targetFileName :: Target -> Text -> FilePath
targetFileName t name = case t of
  Rust -> T.unpack (snake name) ++ "_gen.rs"
  Swift -> T.unpack (pascal name) ++ "Gen.swift"
  Kotlin -> T.unpack (pascal name) ++ "Gen.kt"

-- | §18.1 Only what a peer calls.
--
-- A phone that never authors @add_track@ has no use for its body: the
-- scanner authors it on the server, and the phone receives those entries'
-- effects as facts, because a replica that does not hold a function's
-- closure takes the facts the authority kept beside the entry (§3.8 of the
-- design). So generation may be restricted to the functions a program
-- actually calls — every named function, plus every helper one of them
-- reaches — and the dispatch it emits knows only those. The module bytes
-- and hash are the whole module's regardless: the schema is not optional.
restrict :: [Text] -> Module -> Module
restrict wanted m = m {modFunctions = [fn | fn <- modFunctions m, fnName fn `elem` keep]}
  where
    keep = go [] wanted
    go seen [] = seen
    go seen (n : ns)
      | n `elem` seen = go seen ns
      | otherwise = case lookupFunction m n of
          Just fn -> go (n : seen) (calls fn ++ ns)
          Nothing -> go seen ns

-- | The whole file for one module. The name is the app's ("Harken"). The
-- module bytes and hash are of @whole@; the code is of @m@, which is
-- @whole@ or a 'restrict'ion of it.
generate :: Target -> Text -> Module -> Module -> Text
generate t name whole m =
  T.unlines
    ( header
        ++ [""]
        ++ open
        ++ indentAll (constants ++ [""] ++ concatMap function (modFunctions m) ++ dispatch ++ [""] ++ surface ++ [""] ++ live)
        ++ close
    )
  where
    hashOf fn = hex (functionHash (closure whole fn))
    bytes = encode (toValue whole)
    header =
      [ comment t ("GENERATED by arkc from module " <> hex (moduleHash whole) <> ". Do not edit.")
      , comment t "Every function here is a transcription of the module's IR; the meaning is"
      , comment t "the specification's Ark.Eval, and the library it calls is GENERATED.md."
      ]
        ++ case t of
          Rust -> ["#![allow(unused_variables, unused_mut, clippy::all, non_snake_case)]", "use ark::gen::*;"]
          Swift -> ["import ArkDB"]
          Kotlin -> ["package " <> T.toLower (pascal name) <> ".gen", "", "import dev.arkdb.*"]
    (open, close, indentAll) = case t of
      Rust -> ([], [], id)
      Swift -> (["public enum " <> pascal name <> "Gen {"], ["}"], map ("    " <>))
      Kotlin -> (["object " <> pascal name <> "Gen {"], ["}"], map ("    " <>))
    constants = case t of
      Rust ->
        [ "pub const MODULE_HASH: &str = \"" <> hex (moduleHash whole) <> "\";"
        , "pub const MODULE_BYTES: &str = \"" <> hex bytes <> "\";"
        ]
      Swift ->
        [ "public static let moduleHash = \"" <> hex (moduleHash whole) <> "\""
        , "public static let moduleBytes = \"" <> hex bytes <> "\""
        ]
      Kotlin ->
        [ "const val MODULE_HASH = \"" <> hex (moduleHash whole) <> "\""
        , "const val MODULE_BYTES = \"" <> hex bytes <> "\""
        ]
    function fn = functionCode t fn ++ [""]
    dispatch =
      let mutators = [fn | fn <- modFunctions m, fnKind fn == Mutator]
          queries = [fn | fn <- modFunctions m, fnKind fn == Query]
          arm fn = (hashOf fn, fnName fn)
       in case t of
            Rust ->
              [ "pub fn apply(fn_hash: &str, db: &mut Db, ctx: &Ctx, autos: &Args, args: &Args) -> Result<(), Fault> {"
              , "    match fn_hash {"
              ]
                ++ ["        \"" <> h <> "\" => " <> ident t n <> "(db, ctx, autos, args)," | (h, n) <- map arm mutators]
                ++ [ "        _ => Err(Fault::bug(format!(\"unknown function {fn_hash}\")))," , "    }", "}", ""
                   , "pub fn query(name: &str, db: &Db, args: &Args) -> Result<Value, Fault> {"
                   , "    match name {"
                   ]
                ++ ["        \"" <> fnName fn <> "\" => " <> ident t (fnName fn) <> "(db, args)," | fn <- queries]
                ++ [ "        _ => Err(Fault::bug(format!(\"unknown query {name}\"))),", "    }", "}", ""
                   , "pub const FUNCTIONS: &[(&str, &str)] = &["
                   ]
                ++ ["    (\"" <> fnName fn <> "\", \"" <> hashOf fn <> "\")," | fn <- modFunctions m]
                ++ ["];"]
            Swift ->
              [ "public static func apply(_ fnHash: String, _ db: Store, _ ctx: Ctx, _ autos: Args, _ args: Args) throws {"
              , "    switch fnHash {"
              ]
                ++ ["    case \"" <> h <> "\": try " <> ident t n <> "(db, ctx, autos, args)" | (h, n) <- map arm mutators]
                ++ [ "    default: throw Fault.bug(\"unknown function \\(fnHash)\")", "    }", "}", ""
                   , "public static func query(_ name: String, _ db: Store, _ args: Args) throws -> Value {"
                   , "    switch name {"
                   ]
                ++ ["    case \"" <> fnName fn <> "\": return try " <> ident t (fnName fn) <> "(db, args)" | fn <- queries]
                ++ [ "    default: throw Fault.bug(\"unknown query \\(name)\")", "    }", "}", ""
                   , "public static let functions: [(String, String)] = ["
                   ]
                ++ ["    (\"" <> fnName fn <> "\", \"" <> hashOf fn <> "\")," | fn <- modFunctions m]
                ++ ["]"]
            Kotlin ->
              [ "fun apply(fnHash: String, db: Store, ctx: Ctx, autos: Args, args: Args) {"
              , "    when (fnHash) {"
              ]
                ++ ["        \"" <> h <> "\" -> " <> ident t n <> "(db, ctx, autos, args)" | (h, n) <- map arm mutators]
                ++ [ "        else -> throw Fault.bug(\"unknown function $fnHash\")", "    }", "}", ""
                   , "fun query(name: String, db: Store, args: Args): Value {"
                   , "    return when (name) {"
                   ]
                ++ ["        \"" <> fnName fn <> "\" -> " <> ident t (fnName fn) <> "(db, args)" | fn <- queries]
                ++ [ "        else -> throw Fault.bug(\"unknown query $name\")", "    }", "}", ""
                   , "val FUNCTIONS: List<Pair<String, String>> = listOf("
                   ]
                ++ ["    \"" <> fnName fn <> "\" to \"" <> hashOf fn <> "\"," | fn <- modFunctions m]
                ++ [")"]
    surface = concatMap (argsBuilder t) [fn | fn <- modFunctions m, fnKind fn == Mutator]
    live = concatMap (liveType t) (modLive m)

-- ---------------------------------------------------------------------
-- Functions

functionCode :: Target -> Function -> [Text]
functionCode t fn = [sig] ++ map ("    " <>) (body ++ tailReturn) ++ [closeBrace]
  where
    names = fnNames fn
    ctxK = Ctx' t (fnKind fn) names
    body = concatMap (stmt ctxK) (fnBody fn)
    closeBrace = "}"
    -- A mutator that falls off the end returns nothing.
    tailReturn = case (t, fnKind fn) of
      (Rust, Mutator) -> ["Ok(())"]
      _ -> []
    params = [(ident t n, ty) | (n, ty) <- fnArgs fn]
    sig = case (t, fnKind fn) of
      (Rust, Mutator) -> "pub fn " <> ident t (fnName fn) <> "(db: &mut Db, ctx: &Ctx, autos: &Args, args: &Args) -> Result<(), Fault> {"
      (Rust, Query) -> "pub fn " <> ident t (fnName fn) <> "(db: &Db, args: &Args) -> Result<Value, Fault> {"
      (Rust, Helper) -> "pub fn " <> ident t (fnName fn) <> "(" <> T.intercalate ", " [p <> ": Value" | (p, _) <- params] <> ") -> Result<Value, Fault> {"
      (Swift, Mutator) -> "public static func " <> ident t (fnName fn) <> "(_ db: Store, _ ctx: Ctx, _ autos: Args, _ args: Args) throws {"
      (Swift, Query) -> "public static func " <> ident t (fnName fn) <> "(_ db: Store, _ args: Args) throws -> Value {"
      (Swift, Helper) -> "public static func " <> ident t (fnName fn) <> "(" <> T.intercalate ", " ["_ " <> p <> ": Value" | (p, _) <- params] <> ") throws -> Value {"
      (Kotlin, Mutator) -> "fun " <> ident t (fnName fn) <> "(db: Store, ctx: Ctx, autos: Args, args: Args) {"
      (Kotlin, Query) -> "fun " <> ident t (fnName fn) <> "(db: Store, args: Args): Value {"
      (Kotlin, Helper) -> "fun " <> ident t (fnName fn) <> "(" <> T.intercalate ", " [p <> ": Value" | (p, _) <- params] <> "): Value {"

-- What an expression needs to know about where it is.
data Ctx' = Ctx'
  { cTarget :: Target
  , cKind :: FnKind
  , cNames :: M.Map Sym Text
  }

-- ---------------------------------------------------------------------
-- Statements

stmt :: Ctx' -> Stmt -> [Text]
stmt c = \case
  SLet x e -> case t of
    Rust -> ["let " <> sym c x <> ": Value = " <> expr c e <> ";"]
    Swift -> ["let " <> sym c x <> " = " <> expr c e]
    Kotlin -> ["val " <> sym c x <> " = " <> expr c e]
  SIf cond yes no ->
    let cnd = case t of
          Kotlin -> "if ((" <> expr c cond <> ").asBool()) {"
          _ -> "if (" <> expr c cond <> ")" <> asBool t <> " {"
     in [cnd] ++ map ("    " <>) (concatMap (stmt c) yes) ++ (if null no then [] else ["} else {"] ++ map ("    " <>) (concatMap (stmt c) no)) ++ ["}"]
  SFor x xs body ->
    let hd = case t of
          Rust -> "for " <> sym c x <> " in (" <> expr c xs <> ").as_list() {"
          Swift -> "for " <> sym c x <> " in (" <> expr c xs <> ").asList() {"
          Kotlin -> "for (" <> sym c x <> " in (" <> expr c xs <> ").asList()) {"
     in [hd] ++ map ("    " <>) (concatMap (stmt c) body) ++ ["}"]
  SPut tbl e -> [call t ("db.put(" <> str t tbl <> ", " <> expr c e <> ")") <> semi t]
  SDelete tbl ks -> [call t ("db.delete(" <> str t tbl <> ", " <> listOf t (map (expr c) ks) <> ")") <> semi t]
  SRefuse e -> case t of
    Rust -> ["return Err(Fault::refuse(" <> expr c e <> "));"]
    _ -> ["throw Fault.refuse(" <> expr c e <> ")"]
  SReturn me -> case (t, me) of
    (Rust, Nothing) -> ["return Ok(());"]
    (Rust, Just e) -> ["return Ok(" <> expr c e <> ");"]
    (_, Nothing) -> ["return"]
    (_, Just e) -> ["return " <> expr c e]
  where
    t = cTarget c

-- ---------------------------------------------------------------------
-- Expressions

expr :: Ctx' -> Expr -> Text
expr c = \case
  ELit v -> literal t v
  EArg a -> case cKind c of
    Helper -> ident t a
    _ -> "Ops" <> sep t <> "arg(args, " <> str t a <> ")"
  EAuto a -> "Ops" <> sep t <> "arg(autos, " <> str t a <> ")"
  EVar x -> sym c x
  ECtxUser -> ctxField "user"
  ECtxSession -> ctxField "session"
  EField e f -> "(" <> expr c e <> ").field(" <> str t f <> ")"
  EStruct fs -> record t [(k, expr c e) | (k, e) <- M.toList fs]
  EList es -> valueCtor t "list" [listOf t (map (expr c) es)]
  ESome e -> expr c e
  ENone _ -> valueCtor t "null" []
  EMatch e x a b -> case t of
    Rust -> "Ops::match_opt(" <> expr c e <> ", |" <> sym c x <> "| -> Result<Value, Fault> { Ok(" <> expr c a <> ") }, || -> Result<Value, Fault> { Ok(" <> expr c b <> ") })?"
    Swift -> "try Ops.match(" <> expr c e <> ", { " <> sym c x <> " in " <> expr c a <> " }, { " <> expr c b <> " })"
    Kotlin -> "Ops.match(" <> expr c e <> ", { " <> sym c x <> " -> " <> expr c a <> " }, { " <> expr c b <> " })"
  EIf cond a b -> case t of
    Rust -> "(if (" <> expr c cond <> ").as_bool() { " <> expr c a <> " } else { " <> expr c b <> " })"
    Swift -> "((" <> expr c cond <> ").asBool() ? " <> expr c a <> " : " <> expr c b <> ")"
    Kotlin -> "(if ((" <> expr c cond <> ").asBool()) " <> expr c a <> " else " <> expr c b <> ")"
  EOp And [a, b] -> valueCtor t "bool" ["(" <> expr c a <> ")" <> asBool t <> " && (" <> expr c b <> ")" <> asBool t]
  EOp Or [a, b] -> valueCtor t "bool" ["(" <> expr c a <> ")" <> asBool t <> " || (" <> expr c b <> ")" <> asBool t]
  EOp Not [a] -> "Ops" <> sep t <> "not(" <> expr c a <> ")"
  EOp op es -> call t ("Ops" <> sep t <> opName op <> "(" <> T.intercalate ", " (map (expr c) es) <> ")")
  ECmp op a b -> "Ops" <> sep t <> "cmp(" <> cmpName t op <> ", " <> expr c a <> ", " <> expr c b <> ")"
  ECall n es -> call t (ident t n <> "(" <> T.intercalate ", " (map (expr c) es) <> ")")
  EStd f es -> call t ("Std" <> sep t <> stdName t f <> "(" <> T.intercalate ", " (map (expr c) es) <> ")")
  EMap xs x b -> closureCall "map" xs [x] b
  EFilter xs x b -> closureCall "filter" xs [x] b
  EAny xs x b -> closureCall "any" xs [x] b
  EAll xs x b -> closureCall "all" xs [x] b
  ESortBy xs x k -> closureCall "sort_by" xs [x] k
  EFold xs z acc x b -> case t of
    Rust -> "Ops::fold(" <> expr c xs <> ", " <> expr c z <> ", |" <> sym c acc <> ", " <> sym c x <> "| -> Result<Value, Fault> { Ok(" <> expr c b <> ") })?"
    Swift -> "try Ops.fold(" <> expr c xs <> ", " <> expr c z <> ") { " <> sym c acc <> ", " <> sym c x <> " in " <> expr c b <> " }"
    Kotlin -> "Ops.fold(" <> expr c xs <> ", " <> expr c z <> ") { " <> sym c acc <> ", " <> sym c x <> " -> " <> expr c b <> " }"
  ESelect p -> case t of
    Rust -> "db.select(&" <> plan c p <> ")"
    _ -> "db.select(" <> plan c p <> ")"
  EGet tbl ks -> "db.get(" <> str t tbl <> ", " <> listOf t (map (expr c) ks) <> ")"
  EExists tbl ks -> "db.exists(" <> str t tbl <> ", " <> listOf t (map (expr c) ks) <> ")"
  where
    t = cTarget c
    ctxField f = case t of
      Rust -> "Value::text(ctx." <> f <> ".clone())"
      _ -> "Value.text(ctx." <> f <> ")"
    closureCall name xs binders body = case t of
      Rust -> "Ops::" <> name <> "(" <> expr c xs <> ", |" <> T.intercalate ", " (map (sym c) binders) <> "| -> Result<Value, Fault> { Ok(" <> expr c body <> ") })?"
      Swift -> "try Ops." <> camel name <> "(" <> expr c xs <> ") { " <> T.intercalate ", " (map (sym c) binders) <> " in " <> expr c body <> " }"
      Kotlin -> "Ops." <> camel name <> "(" <> expr c xs <> ") { " <> T.intercalate ", " (map (sym c) binders) <> " -> " <> expr c body <> " }"

plan :: Ctx' -> Plan -> Text
plan c p =
  "Plan" <> sep t <> "from(" <> str t (pTable p) <> ")"
    <> maybe "" (\f -> ".filter(" <> predicate c f <> ")") (pFilter p)
    <> T.concat ["." <> orderBy <> "(" <> str t col <> ", " <> dirName t d <> ")" | (col, d) <- pOrder p]
    <> maybe "" (\n -> ".limit(" <> T.pack (show n) <> ")") (pLimit p)
    <> T.concat
      [ ".related(" <> str t (rName r) <> ", " <> str t (relParent (rRelation r)) <> ", " <> str t (relChild (rRelation r)) <> ", " <> str t (relColumn (rRelation r)) <> ", " <> plan c (rPlan r) <> ")"
      | r <- pRelated p
      ]
  where
    t = cTarget c
    orderBy = case t of Rust -> "order_by"; _ -> "orderBy"

predicate :: Ctx' -> Pred -> Text
predicate c = \case
  PCmp col op e -> "Pred" <> sep t <> "cmp(" <> str t col <> ", " <> cmpName t op <> ", " <> expr c e <> ")"
  PIn col es -> "Pred" <> sep t <> inList <> "(" <> str t col <> ", " <> listOf t (map (expr c) es) <> ")"
  PAll ps -> "Pred" <> sep t <> "all(" <> listOf t (map (predicate c) ps) <> ")"
  PAny ps -> "Pred" <> sep t <> "any(" <> listOf t (map (predicate c) ps) <> ")"
  PNot q -> "Pred" <> sep t <> "not(" <> predicate c q <> ")"
  where
    t = cTarget c
    inList = case t of Rust -> "in_list"; _ -> "inList"

-- ---------------------------------------------------------------------
-- The typed call surface and the live types

argsBuilder :: Target -> Function -> [Text]
argsBuilder t fn = case t of
  Rust ->
    [ "pub fn " <> ident t (fnName fn) <> "_args(" <> T.intercalate ", " [ident t n <> ": " <> langTy t ty | (n, ty) <- fnArgs fn] <> ") -> Args {"
    , "    Args::from([" <> T.intercalate ", " ["(" <> str t n <> ".to_string(), " <> toValue' t ty (ident t n) <> ")" | (n, ty) <- fnArgs fn] <> "])"
    , "}"
    , ""
    ]
  Swift ->
    [ "public static func " <> ident t (fnName fn) <> "Args(" <> T.intercalate ", " [ident t n <> ": " <> langTy t ty | (n, ty) <- fnArgs fn] <> ") -> Args {"
    , "    return [" <> (if null (fnArgs fn) then ":" else T.intercalate ", " [str t n <> ": " <> toValue' t ty (ident t n) | (n, ty) <- fnArgs fn]) <> "]"
    , "}"
    , ""
    ]
  Kotlin ->
    [ "fun " <> ident t (fnName fn) <> "Args(" <> T.intercalate ", " [ident t n <> ": " <> langTy t ty | (n, ty) <- fnArgs fn] <> "): Args ="
    , "    mapOf(" <> T.intercalate ", " [str t n <> " to " <> toValue' t ty (ident t n) | (n, ty) <- fnArgs fn] <> ")"
    , ""
    ]

-- The app-facing type of an argument, and how it becomes a Value.
langTy :: Target -> Ty -> Text
langTy t = \case
  TBool -> case t of Rust -> "bool"; Swift -> "Bool"; Kotlin -> "Boolean"
  TInt -> case t of Rust -> "i64"; Swift -> "Int64"; Kotlin -> "Long"
  TText -> "String"
  TBytes -> case t of Rust -> "Vec<u8>"; Swift -> "[UInt8]"; Kotlin -> "ByteArray"
  TId _ -> "Id"
  TEnum _ -> "String"
  TOption x -> case t of Rust -> "Option<" <> langTy t x <> ">"; _ -> langTy t x <> "?"
  TList x -> case t of Rust -> "Vec<" <> langTy t x <> ">"; Swift -> "[" <> langTy t x <> "]"; Kotlin -> "List<" <> langTy t x <> ">"
  TStruct _ -> "Value"

toValue' :: Target -> Ty -> Text -> Text
toValue' t ty v = case ty of
  TBool -> valueCtor t "bool" [v]
  TInt -> valueCtor t "int" [v]
  TText -> valueCtor t "text" [v]
  TBytes -> valueCtor t "bytes" [v]
  TId _ -> valueCtor t "id" [v]
  TEnum _ -> valueCtor t "text" [v]
  TStruct _ -> v
  TOption x -> case t of
    Rust -> "Value::opt(" <> v <> ".map(|x| " <> toValue' t x "x" <> "))"
    Swift -> "Value.opt(" <> v <> ".map { x in " <> toValue' t x "x" <> " })"
    Kotlin -> "Value.opt(" <> v <> "?.let { x -> " <> toValue' t x "x" <> " })"
  TList x -> case t of
    Rust -> "Value::list(" <> v <> ".into_iter().map(|x| " <> toValue' t x "x" <> ").collect())"
    Swift -> "Value.list(" <> v <> ".map { x in " <> toValue' t x "x" <> " })"
    Kotlin -> "Value.list(" <> v <> ".map { x -> " <> toValue' t x "x" <> " })"

-- A live frame type: a typed record with a Value on each side, so no
-- client mirrors it by hand. Only structs of scalars (and options of them)
-- are given a record type; anything else is left as a Value with a note.
liveType :: Target -> (Text, Ty) -> [Text]
liveType t (name, ty) = case ty of
  TStruct fs | all scalarish (M.elems fs) ->
    let fields = M.toList fs
     in case t of
          Rust ->
            [ "#[derive(Debug, Clone)]"
            , "pub struct " <> pascal name <> " {"
            ]
              ++ ["    pub " <> ident t k <> ": " <> langTy t v <> "," | (k, v) <- fields]
              ++ [ "}"
                 , "impl " <> pascal name <> " {"
                 , "    pub fn to_value(&self) -> Value {"
                 , "        Value::record(vec![" <> T.intercalate ", " ["(" <> str t k <> ".to_string(), " <> toValue' t v ("self." <> ident t k <> ".clone()") <> ")" | (k, v) <- fields] <> "])"
                 , "    }"
                 , "}"
                 , ""
                 ]
          Swift ->
            ["public struct " <> pascal name <> " {"]
              ++ ["    public var " <> ident t k <> ": " <> langTy t v | (k, v) <- fields]
              ++ [ "    public func toValue() -> Value {"
                 , "        return Value.record([" <> T.intercalate ", " ["(" <> str t k <> ", " <> toValue' t v (ident t k) <> ")" | (k, v) <- fields] <> "])"
                 , "    }"
                 , "}"
                 , ""
                 ]
          Kotlin ->
            [ "data class " <> pascal name <> "(" <> T.intercalate ", " ["val " <> ident t k <> ": " <> langTy t v | (k, v) <- fields] <> ") {"
            , "    fun toValue(): Value = Value.record(listOf(" <> T.intercalate ", " [str t k <> " to " <> toValue' t v (ident t k) | (k, v) <- fields] <> "))"
            , "}"
            , ""
            ]
  _ -> [comment t ("live type " <> name <> " is carried as a Value: " <> T.pack (show ty)), ""]
  where
    scalarish = \case
      TOption x -> isScalar x
      TList x -> isScalar x
      x -> isScalar x

-- ---------------------------------------------------------------------
-- Spelling

comment :: Target -> Text -> Text
comment _ s = "// " <> s

sep :: Target -> Text
sep Rust = "::"
sep _ = "."

semi :: Target -> Text
semi Rust = ";"
semi _ = ""

-- Wrap a call that may fault.
call :: Target -> Text -> Text
call Rust e = e <> "?"
call Swift e = "try " <> e
call Kotlin e = e

asBool :: Target -> Text
asBool Rust = ".as_bool()"
asBool _ = ".asBool()"

-- | A @Value@ constructor call. Kotlin cannot spell @null@ as a function
-- name without backticks, so there it is @Value.`null`()@ — the one
-- deviation the Kotlin runtime records.
valueCtor :: Target -> Text -> [Text] -> Text
valueCtor t name args = "Value" <> sep t <> name' <> "(" <> T.intercalate ", " args <> ")"
  where
    name' = case (t, name) of
      (Kotlin, "null") -> "`null`"
      (Rust, n) -> snake n
      (_, n) -> n

listOf :: Target -> [Text] -> Text
listOf Rust xs = "vec![" <> T.intercalate ", " xs <> "]"
listOf Swift xs = "[" <> T.intercalate ", " xs <> "]"
listOf Kotlin xs = "listOf(" <> T.intercalate ", " xs <> ")"

record :: Target -> [(Text, Text)] -> Text
record t kvs = case t of
  Rust -> "Value::record(vec![" <> T.intercalate ", " ["(" <> str t k <> ".to_string(), " <> v <> ")" | (k, v) <- kvs] <> "])"
  Swift -> "Value.record([" <> T.intercalate ", " ["(" <> str t k <> ", " <> v <> ")" | (k, v) <- kvs] <> "])"
  Kotlin -> "Value.record(listOf(" <> T.intercalate ", " [str t k <> " to " <> v | (k, v) <- kvs] <> "))"

opName :: Op -> Text
opName = \case
  Add -> "add"
  Sub -> "sub"
  Mul -> "mul"
  Div -> "div"
  Mod -> "mod"
  Neg -> "neg"
  And -> "and"
  Or -> "or"
  Not -> "not"

cmpName :: Target -> CmpOp -> Text
cmpName t op = "CmpOp" <> sep t <> case t of
  Swift -> T.toLower (T.pack (show op))
  _ -> T.pack (show op)

dirName :: Target -> Dir -> Text
dirName t d = "Dir" <> sep t <> case t of
  Swift -> T.toLower (T.pack (show d))
  _ -> T.pack (show d)

stdName :: Target -> StdFn -> Text
stdName t f = case t of
  Rust -> snake (T.pack (show f))
  _ -> lowerFirst (T.pack (show f))

-- | Literals. Integers at the edge of the range are spelled by name,
-- because @-9223372036854775808@ is not a literal in Kotlin or Rust.
literal :: Target -> Value -> Text
literal t = \case
  VNull -> valueCtor t "null" []
  VBool b -> valueCtor t "bool" [if b then "true" else "false"]
  VInt n
    | n == minBound -> valueCtor t "int" [case t of Rust -> "i64::MIN"; Swift -> "Int64.min"; Kotlin -> "Long.MIN_VALUE"]
    | otherwise -> valueCtor t "int" [T.pack (show n) <> (if t == Kotlin then "L" else "")]
  VText s -> valueCtor t "text" [str t s]
  VBytes b -> valueCtor t "bytesHex" [str t (hex b)]
  VId i -> valueCtor t "idHex" [str t (hex (idBytes i))]
  VList vs -> valueCtor t "list" [listOf t (map (literal t) vs)]
  VStruct m -> record t [(k, literal t v) | (k, v) <- M.toList m]

-- | A string literal. Non-ASCII is left as UTF-8, which all three compilers
-- read; controls, quotes and backslashes are escaped; Kotlin's @$@ too.
str :: Target -> Text -> Text
str t s = "\"" <> T.concatMap esc s <> "\""
  where
    esc ch
      | ch == '"' = "\\\""
      | ch == '\\' = "\\\\"
      | ch == '\n' = "\\n"
      | ch == '\t' = "\\t"
      | ch == '\r' = "\\r"
      | ch == '$' && t == Kotlin = "\\$"
      | ord ch < 0x20 = case t of
          Kotlin -> "\\u" <> T.justifyRight 4 '0' (T.pack (showHex (ord ch) ""))
          _ -> "\\u{" <> T.pack (showHex (ord ch) "") <> "}"
      | otherwise = T.singleton ch

hex :: B.ByteString -> Text
hex = T.pack . concatMap (\w -> let s = showHex w "" in if length s == 1 then '0' : s else s) . B.unpack

-- | The name of a function or argument in a target, from the module's
-- snake_case: Rust keeps it, the others camel it; keywords get a suffix.
ident :: Target -> Text -> Text
ident t n = avoidKeyword t (case t of Rust -> snake n; _ -> camel n)

-- | A local's name: the author's if the module carried it, else @v<n>@.
sym :: Ctx' -> Sym -> Text
sym c x = case M.lookup x (cNames c) of
  Just n | not (T.null n) -> ident (cTarget c) (T.filter (\ch -> isAlphaNum ch || ch == '_') n)
  _ -> "v" <> T.pack (show x)

avoidKeyword :: Target -> Text -> Text
avoidKeyword t n
  | n `elem` keywords t = n <> "_"
  | otherwise = n
  where
    keywords Rust = ["as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref", "return", "self", "static", "struct", "super", "trait", "true", "type", "unsafe", "use", "where", "while", "async", "await", "dyn"]
    keywords Swift = ["as", "break", "case", "catch", "class", "continue", "default", "defer", "do", "else", "enum", "extension", "false", "for", "func", "guard", "if", "import", "in", "init", "is", "let", "nil", "protocol", "public", "repeat", "return", "self", "static", "struct", "switch", "throw", "throws", "true", "try", "var", "where", "while", "operator", "inout"]
    keywords Kotlin = ["as", "break", "class", "continue", "do", "else", "false", "for", "fun", "if", "in", "interface", "is", "null", "object", "package", "return", "super", "this", "throw", "true", "try", "typealias", "val", "var", "when", "while", "when"]

snake :: Text -> Text
snake s = T.pack (go True (T.unpack s))
  where
    go _ [] = []
    go first (a : rest)
      | isUpper a = (if first then id else ('_' :)) (toLower a : go False rest)
      | otherwise = a : go False rest

camel :: Text -> Text
camel s = lowerFirst (pascal s)

pascal :: Text -> Text
pascal s = T.concat [capitalise part | part <- T.splitOn "_" s, not (T.null part)]
  where
    capitalise p = T.cons (toUpper (T.head p)) (T.tail p)

lowerFirst :: Text -> Text
lowerFirst s
  | T.null s = s
  | otherwise = T.cons (toLower (T.head s)) (T.tail s)

