//! §5 The standard library, as `Ark.Std` defines it.
//!
//! Everything a function may compute that is not an operator or a read.
//! `trim`, `lower` and `is_alnum` consult the pinned Unicode tables in
//! [`crate::unicode_tables`] (UCD 16.0.0, generated by the spec) and
//! nothing of the platform.
//!
//! The module is named `stdlib` rather than `std` so that `std::` paths in
//! this crate stay unambiguous.

use std::collections::BTreeMap;

use crate::ir::StdFn;
use crate::sha256::sha256;
use crate::unicode_tables::{is_alphanumeric, is_white_space, to_lower_simple};
use crate::value::{hex, Id, Value};

/// A fault a standard function can report (`Ark.Std.StdError`). `Arity`
/// and `TypeMismatch` are bugs; `Fault` is a deterministic verdict.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum StdError {
    Arity(StdFn, usize),
    TypeMismatch(StdFn),
    Fault(String),
}

/// Apply a standard function to already-evaluated arguments (`Ark.Std.std`).
pub fn std(f: StdFn, args: &[Value]) -> Result<Value, StdError> {
    use StdFn::*;
    use Value::*;
    let mismatch = || Err(StdError::TypeMismatch(f));
    if args.len() != f.arity() {
        return Err(StdError::Arity(f, args.len()));
    }
    match (f, args) {
        // text
        (Trim, [Text(t)]) => Ok(Text(t.trim_matches(is_white_space).to_string())),
        (IsEmpty, [Text(t)]) => Ok(Bool(t.is_empty())),
        (Concat, [List(xs)]) => {
            let mut out = String::new();
            for x in xs {
                match x {
                    Text(t) => out.push_str(t),
                    _ => return mismatch(),
                }
            }
            Ok(Text(out))
        }
        (Lower, [Text(t)]) => Ok(Text(t.chars().map(to_lower_simple).collect())),
        (IsAlnum, [Text(t)]) => Ok(Bool(!t.is_empty() && t.chars().all(is_alphanumeric))),
        (Chars, [Text(t)]) => Ok(List(t.chars().map(|c| Text(c.to_string())).collect())),
        (TextLen, [Text(t)]) => Ok(Int(t.chars().count() as i64)),
        (StartsWith, [Text(t), Text(p)]) => Ok(Bool(t.starts_with(p.as_str()))),
        (SplitOnce, [Text(t), Text(sep)]) => {
            if sep.is_empty() {
                return Ok(Null);
            }
            Ok(match t.split_once(sep.as_str()) {
                None => Null,
                Some((before, after)) => Value::record(vec![("before", Text(before.to_string())), ("after", Text(after.to_string()))]),
            })
        }
        (TextOfInt, [Int(n)]) => Ok(Text(n.to_string())),
        (Hex, [Bytes(b)]) => Ok(Text(hex(b))),
        // int
        (Min, [Int(a), Int(b)]) => Ok(Int(*a.min(b))),
        (Max, [Int(a), Int(b)]) => Ok(Int(*a.max(b))),
        (Clamp, [Int(x), Int(lo), Int(hi)]) => {
            if lo > hi {
                Err(StdError::Fault("clamp: lower bound above upper bound".into()))
            } else {
                Ok(Int(*lo.max(hi.min(x))))
            }
        }
        (Abs, [Int(n)]) => {
            if *n == i64::MIN {
                Err(StdError::Fault("integer overflow".into()))
            } else {
                Ok(Int(n.abs()))
            }
        }
        // hash
        (Fnv1a64, [Text(t)]) => Ok(Int(fnv1a64(t.as_bytes()) as i64)),
        (Sha256, [Bytes(b)]) => Ok(Bytes(sha256(b))),
        // id
        (IdOfText, [Text(t)]) => Ok(id_of_text(t).map(Value::Id).unwrap_or(Null)),
        (TextOfId, [Value::Id(i)]) => Ok(Text(text_of_id(i))),
        (NilId, []) => Ok(Value::Id([0; 16])),
        (Utf8, [Text(t)]) => Ok(Bytes(t.as_bytes().to_vec())),
        // list and option
        (First, [List(xs)]) => Ok(xs.first().cloned().unwrap_or(Null)),
        (Last, [List(xs)]) => Ok(xs.last().cloned().unwrap_or(Null)),
        (Len, [List(xs)]) => Ok(Int(xs.len() as i64)),
        (Contains, [List(xs), v]) => Ok(Bool(xs.iter().any(|x| x == v))),
        (Reverse, [List(xs)]) => Ok(List(xs.iter().rev().cloned().collect())),
        (IsSome, [v]) => Ok(Bool(!v.is_null())),
        (UnwrapOr, [Null, d]) => Ok(d.clone()),
        (UnwrapOr, [v, _]) => Ok(v.clone()),
        (Unwrap, [Null]) => Err(StdError::Fault("unwrapped none".into())),
        (Unwrap, [v]) => Ok(v.clone()),
        _ => mismatch(),
    }
}

/// FNV-1a, 64-bit: offset basis `0xcbf29ce484222325`, prime
/// `0x00000100000001b3`, over the bytes in order.
pub fn fnv1a64(bytes: &[u8]) -> u64 {
    bytes
        .iter()
        .fold(0xcbf29ce484222325u64, |h, b| (h ^ (*b as u64)).wrapping_mul(0x00000100000001b3))
}

/// The canonical text of an id: lowercase 8-4-4-4-12.
pub fn text_of_id(i: &Id) -> String {
    let h = hex(i);
    format!("{}-{}-{}-{}-{}", &h[..8], &h[8..12], &h[12..16], &h[16..20], &h[20..])
}

/// Parse 8-4-4-4-12 hex in either case; anything else is `None`.
pub fn id_of_text(t: &str) -> Option<Id> {
    let parts: Vec<&str> = t.split('-').collect();
    if parts.len() != 5 {
        return None;
    }
    let lens = [8, 4, 4, 4, 12];
    for (p, want) in parts.iter().zip(lens) {
        if p.chars().count() != want || !p.chars().all(|c| c.is_ascii_hexdigit()) {
            return None;
        }
    }
    let bytes = crate::value::decode_hex(&parts.concat())?;
    bytes.as_slice().try_into().ok()
}

/// Arguments (or autos) by name (`Ark.Eval.Args`).
pub type Args = BTreeMap<String, Value>;

#[cfg(test)]
mod tests {
    use super::*;

    fn call(f: StdFn, args: &[Value]) -> Result<Value, StdError> {
        std(f, args)
    }

    #[test]
    fn unicode_goes_through_the_tables() {
        assert_eq!(call(StdFn::Trim, &[Value::text("\u{3000} a \u{85}")]).unwrap(), Value::text("a"));
        assert_eq!(call(StdFn::Lower, &[Value::text("İ")]).unwrap(), Value::text("i"));
        assert_eq!(call(StdFn::IsAlnum, &[Value::text("Ⅻ٣")]).unwrap(), Value::bool(true));
        assert_eq!(call(StdFn::IsAlnum, &[Value::text("")]).unwrap(), Value::bool(false));
    }

    #[test]
    fn hashes_and_ids() {
        assert_eq!(fnv1a64(b""), 0xcbf29ce484222325);
        assert_eq!(fnv1a64(b"a"), 0xaf63dc4c8601ec8c);
        let id = call(StdFn::IdOfText, &[Value::text("00000000-0000-0000-0000-00000000000A")]).unwrap();
        assert_eq!(call(StdFn::TextOfId, &[id]).unwrap(), Value::text("00000000-0000-0000-0000-00000000000a"));
        assert_eq!(call(StdFn::IdOfText, &[Value::text("nope")]).unwrap(), Value::Null);
    }

    #[test]
    fn faults_are_told_apart() {
        assert_eq!(call(StdFn::Abs, &[Value::int(i64::MIN)]), Err(StdError::Fault("integer overflow".into())));
        assert_eq!(
            call(StdFn::Clamp, &[Value::int(1), Value::int(2), Value::int(1)]),
            Err(StdError::Fault("clamp: lower bound above upper bound".into()))
        );
        assert!(matches!(call(StdFn::Trim, &[Value::int(1)]), Err(StdError::TypeMismatch(_))));
        assert_eq!(
            call(StdFn::SplitOnce, &[Value::text("a=b=c"), Value::text("=")]).unwrap(),
            Value::record(vec![("before", Value::text("a")), ("after", Value::text("b=c"))])
        );
        assert_eq!(call(StdFn::SplitOnce, &[Value::text("abc"), Value::text("")]).unwrap(), Value::Null);
        assert_eq!(call(StdFn::Unwrap, &[Value::Null]), Err(StdError::Fault("unwrapped none".into())));
        assert_eq!(call(StdFn::Unwrap, &[Value::int(3)]), Ok(Value::int(3)));
    }
}
