//! §5 The standard library, as `Ark.Std` defines it.
//!
//! Everything a function may compute that is not an operator or a read.
//! `trim`, `lower` and `is_alnum` consult the pinned Unicode tables in
//! [`crate::unicode_tables`] (UCD 16.0.0, generated by the spec) and
//! nothing of the platform.
//!
//! The module is named `stdlib` rather than `std` so that `std::` paths in
//! this crate stay unambiguous; the unit struct generated code calls is
//! [`Std`], as GENERATED.md spells it (`Std::trim(a)?`).

use std::collections::BTreeMap;

use crate::fault::Fault;
use crate::ir::StdFn;
use crate::sha256::sha256;
use crate::unicode_tables::{is_alphanumeric, is_white_space, to_lower_simple};
use crate::value::{hex, Id, Value};

/// A fault a standard function can report (`Ark.Std.StdError`). `Arity`
/// and `TypeMismatch` are bugs; `Fault` is a deterministic verdict.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum StdError {
    Arity(StdFn, usize),
    TypeMismatch(StdFn),
    Fault(String),
}

impl From<StdError> for Fault {
    fn from(e: StdError) -> Fault {
        match e {
            StdError::Arity(f, n) => Fault::bug(format!("{}/{n}: wrong number of arguments", f.show())),
            StdError::TypeMismatch(f) => Fault::bug(format!("{}: type mismatch", f.show())),
            StdError::Fault(t) => Fault::refuse(t),
        }
    }
}

/// Apply a standard function to already-evaluated arguments (`Ark.Std.std`).
pub fn std(f: StdFn, args: &[Value]) -> Result<Value, StdError> {
    use StdFn::*;
    use Value::*;
    let mismatch = || Err(StdError::TypeMismatch(f));
    if args.len() != f.arity() {
        return Err(StdError::Arity(f, args.len()));
    }
    match (f, args) {
        // text
        (Trim, [Text(t)]) => Ok(Text(t.trim_matches(is_white_space).to_string())),
        (IsEmpty, [Text(t)]) => Ok(Bool(t.is_empty())),
        (Concat, [List(xs)]) => {
            let mut out = String::new();
            for x in xs {
                match x {
                    Text(t) => out.push_str(t),
                    _ => return mismatch(),
                }
            }
            Ok(Text(out))
        }
        (Lower, [Text(t)]) => Ok(Text(t.chars().map(to_lower_simple).collect())),
        (IsAlnum, [Text(t)]) => Ok(Bool(!t.is_empty() && t.chars().all(is_alphanumeric))),
        (Chars, [Text(t)]) => Ok(List(t.chars().map(|c| Text(c.to_string())).collect())),
        (TextLen, [Text(t)]) => Ok(Int(t.chars().count() as i64)),
        (StartsWith, [Text(t), Text(p)]) => Ok(Bool(t.starts_with(p.as_str()))),
        (SplitOnce, [Text(t), Text(sep)]) => {
            if sep.is_empty() {
                return Ok(Null);
            }
            Ok(match t.split_once(sep.as_str()) {
                None => Null,
                Some((before, after)) => Value::record(vec![("before", Text(before.to_string())), ("after", Text(after.to_string()))]),
            })
        }
        (TextOfInt, [Int(n)]) => Ok(Text(n.to_string())),
        (Hex, [Bytes(b)]) => Ok(Text(hex(b))),
        // int
        (Min, [Int(a), Int(b)]) => Ok(Int(*a.min(b))),
        (Max, [Int(a), Int(b)]) => Ok(Int(*a.max(b))),
        (Clamp, [Int(x), Int(lo), Int(hi)]) => {
            if lo > hi {
                Err(StdError::Fault("clamp: lower bound above upper bound".into()))
            } else {
                Ok(Int(*lo.max(hi.min(x))))
            }
        }
        (Abs, [Int(n)]) => {
            if *n == i64::MIN {
                Err(StdError::Fault("integer overflow".into()))
            } else {
                Ok(Int(n.abs()))
            }
        }
        // hash
        (Fnv1a64, [Text(t)]) => Ok(Int(fnv1a64(t.as_bytes()) as i64)),
        (Sha256, [Bytes(b)]) => Ok(Bytes(sha256(b))),
        // id
        (IdOfText, [Text(t)]) => Ok(id_of_text(t).map(Value::Id).unwrap_or(Null)),
        (TextOfId, [Value::Id(i)]) => Ok(Text(text_of_id(i))),
        (NilId, []) => Ok(Value::Id([0; 16])),
        (Utf8, [Text(t)]) => Ok(Bytes(t.as_bytes().to_vec())),
        // list and option
        (First, [List(xs)]) => Ok(xs.first().cloned().unwrap_or(Null)),
        (Last, [List(xs)]) => Ok(xs.last().cloned().unwrap_or(Null)),
        (Len, [List(xs)]) => Ok(Int(xs.len() as i64)),
        (Contains, [List(xs), v]) => Ok(Bool(xs.iter().any(|x| x == v))),
        (Reverse, [List(xs)]) => Ok(List(xs.iter().rev().cloned().collect())),
        (IsSome, [v]) => Ok(Bool(!v.is_null())),
        (UnwrapOr, [Null, d]) => Ok(d.clone()),
        (UnwrapOr, [v, _]) => Ok(v.clone()),
        _ => mismatch(),
    }
}

/// FNV-1a, 64-bit: offset basis `0xcbf29ce484222325`, prime
/// `0x00000100000001b3`, over the bytes in order.
pub fn fnv1a64(bytes: &[u8]) -> u64 {
    bytes
        .iter()
        .fold(0xcbf29ce484222325u64, |h, b| (h ^ (*b as u64)).wrapping_mul(0x00000100000001b3))
}

/// The canonical text of an id: lowercase 8-4-4-4-12.
pub fn text_of_id(i: &Id) -> String {
    let h = hex(i);
    format!("{}-{}-{}-{}-{}", &h[..8], &h[8..12], &h[12..16], &h[16..20], &h[20..])
}

/// Parse 8-4-4-4-12 hex in either case; anything else is `None`.
pub fn id_of_text(t: &str) -> Option<Id> {
    let parts: Vec<&str> = t.split('-').collect();
    if parts.len() != 5 {
        return None;
    }
    let lens = [8, 4, 4, 4, 12];
    for (p, want) in parts.iter().zip(lens) {
        if p.chars().count() != want || !p.chars().all(|c| c.is_ascii_hexdigit()) {
            return None;
        }
    }
    let bytes = crate::value::decode_hex(&parts.concat())?;
    bytes.as_slice().try_into().ok()
}

/// The standard library as GENERATED.md spells it: one associated function
/// per [`StdFn`], each over `Value`s, each `Result<Value, Fault>`. A type
/// mismatch or an arity error is a [`Fault::Bug`]; a deterministic fault
/// (an overflow, crossed clamp bounds) is a [`Fault::Refuse`].
pub struct Std;

macro_rules! std_fn {
    ($(#[$doc:meta])* $name:ident, $variant:ident, ($($arg:ident),*)) => {
        $(#[$doc])*
        pub fn $name($($arg: Value),*) -> Result<Value, Fault> {
            Ok(std(StdFn::$variant, &[$($arg),*])?)
        }
    };
}

impl Std {
    std_fn!(/// Strip White_Space from both ends.
        trim, Trim, (a));
    std_fn!(/// Whether a text is empty.
        is_empty, IsEmpty, (a));
    std_fn!(/// The concatenation of a list of texts.
        concat, Concat, (a));
    std_fn!(/// Simple lowercase mapping, code point by code point.
        lower, Lower, (a));
    std_fn!(/// Non-empty and every code point Alphabetic or numeric.
        is_alnum, IsAlnum, (a));
    std_fn!(/// The code points, each as a one-character text.
        chars, Chars, (a));
    std_fn!(/// The length in code points.
        text_len, TextLen, (a));
    std_fn!(/// Whether the first text starts with the second.
        starts_with, StartsWith, (a, b));
    std_fn!(/// Split at the first occurrence: `Some {before, after}` or `None`.
        split_once, SplitOnce, (a, b));
    std_fn!(/// Decimal, with a leading `-` for negatives.
        text_of_int, TextOfInt, (a));
    std_fn!(/// Lowercase hex, two digits per byte.
        hex, Hex, (a));
    std_fn!(/// The smaller int.
        min, Min, (a, b));
    std_fn!(/// The larger int.
        max, Max, (a, b));
    std_fn!(/// `x` held between `lo` and `hi`; faults when `lo > hi`.
        clamp, Clamp, (x, lo, hi));
    std_fn!(/// The absolute value; faults on `MIN`.
        abs, Abs, (a));
    std_fn!(/// FNV-1a of a text's UTF-8 bytes, the u64 reinterpreted as an int.
        fnv1a64, Fnv1a64, (a));
    std_fn!(/// SHA-256 of bytes, as 32 bytes.
        sha256, Sha256, (a));
    std_fn!(/// Parse 8-4-4-4-12 hex; `None` if not an id.
        id_of_text, IdOfText, (a));
    std_fn!(/// Canonical lowercase 8-4-4-4-12.
        text_of_id, TextOfId, (a));
    std_fn!(/// The all-zero id.
        nil_id, NilId, ());
    std_fn!(/// A text's UTF-8 bytes.
        utf8, Utf8, (a));
    std_fn!(/// The first element, or `None`.
        first, First, (a));
    std_fn!(/// The last element, or `None`.
        last, Last, (a));
    std_fn!(/// The length of a list.
        len, Len, (a));
    std_fn!(/// Whether a list holds a value equal to the second argument.
        contains, Contains, (a, b));
    std_fn!(/// The list reversed.
        reverse, Reverse, (a));
    std_fn!(/// Whether an option is `Some`.
        is_some, IsSome, (a));
    std_fn!(/// The option's value, or the default.
        unwrap_or, UnwrapOr, (a, b));
}

/// Arguments (or autos) by name (`Ark.Eval.Args`).
pub type Args = BTreeMap<String, Value>;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn unicode_goes_through_the_tables() {
        assert_eq!(Std::trim(Value::text("\u{3000} a \u{85}")).unwrap(), Value::text("a"));
        assert_eq!(Std::lower(Value::text("İ")).unwrap(), Value::text("i"));
        assert_eq!(Std::is_alnum(Value::text("Ⅻ٣")).unwrap(), Value::bool(true));
        assert_eq!(Std::is_alnum(Value::text("")).unwrap(), Value::bool(false));
    }

    #[test]
    fn hashes_and_ids() {
        assert_eq!(fnv1a64(b""), 0xcbf29ce484222325);
        assert_eq!(fnv1a64(b"a"), 0xaf63dc4c8601ec8c);
        let id = Std::id_of_text(Value::text("00000000-0000-0000-0000-00000000000A")).unwrap();
        assert_eq!(Std::text_of_id(id).unwrap(), Value::text("00000000-0000-0000-0000-00000000000a"));
        assert_eq!(Std::id_of_text(Value::text("nope")).unwrap(), Value::Null);
    }

    #[test]
    fn faults_are_told_apart() {
        assert_eq!(Std::abs(Value::int(i64::MIN)), Err(Fault::refuse("integer overflow")));
        assert_eq!(
            Std::clamp(Value::int(1), Value::int(2), Value::int(1)),
            Err(Fault::refuse("clamp: lower bound above upper bound"))
        );
        assert!(matches!(Std::trim(Value::int(1)), Err(Fault::Bug(_))));
        assert_eq!(
            Std::split_once(Value::text("a=b=c"), Value::text("=")).unwrap(),
            Value::record(vec![("before", Value::text("a")), ("after", Value::text("b=c"))])
        );
        assert_eq!(Std::split_once(Value::text("abc"), Value::text("")).unwrap(), Value::Null);
    }
}
