#![forbid(unsafe_code)]
//! harken's browser peer: an [`ark::protocol::Client`] holding the `library`
//! and `playlists` scopes, compiled to wasm and driven from TypeScript.
//!
//! It is the desktop's `peer.rs` with the platform taken out. Everything
//! that touches the world — the socket, the clock, the random bytes, the
//! place the scopes are kept — is either supplied by the page or asked of
//! the browser through `js-sys`; what is left is the engine's state machine
//! and the two things a screen needs of it, `mutate` and `query`.
//!
//! **Every entry is applied through the interpreter**, over the closures
//! of the module this crate embeds (`include_bytes!` of
//! `harken/domain/harken.ark`), which is exactly how the server applies
//! them (`ark::hash::closures`, `ark::eval::apply_closure`). Authoring is
//! by name through that same closure, the way the desktop's
//! `author_by_intent` does it; native procedures are the follow-up once the
//! new authoring API lands (README.md).
//!
//! Alone — no server URL — the peer is an [`Authority`] for each of its
//! scopes and sequences its own intents with `local_commit`, as the desktop
//! does; nothing is ever pending for long.

use std::collections::BTreeMap;

use ark::canon;
use ark::eval::{Args, Ctx};
use ark::hash::{closures, module_hash, Closure, FnHash};
use ark::ir::decode::module_from_value;
use ark::ir::{Auto, FnKind, Function, Module};
use ark::log::{snapshot_of, Entry, Log, Seq};
use ark::peer::{local_commit, Authority, Changes, Replica};
use ark::protocol::{entry_from_value, entry_value, Client, Mode, ServerMsg};
use ark::schema::{Schema, ScopeName, Ty};
use ark::stdlib::{id_of_text, text_of_id};
use ark::store::{MemoryStore, Refusal, Store};
use ark::value::{decode_hex, hex, Id, Value};
use js_sys::{Array, Function as JsFunction, Uint8Array};
use serde_json::{json, Map as JsonMap, Value as Json};
use wasm_bindgen::prelude::*;

/// The domain, as the domain program wrote it. Regenerated by
/// `nix build .#harken-domain`; the path is the contract.
const MODULE_BYTES: &[u8] = include_bytes!("../../domain/harken.ark");

/// Dev auth: a name is a login, and every login is the session `dev`
/// (harken/server/README.md).
const SESSION: &str = "dev";

/// Beyond this an `Int` is a string in JSON, because a JS number is a
/// double and would round it.
const SAFE_INT: i64 = 1 << 53;

// -- the module -------------------------------------------------------------

fn load_module() -> Result<Module, String> {
    let v = canon::decode(MODULE_BYTES).map_err(|e| format!("module: {e}"))?;
    module_from_value(&v).map_err(|e| format!("module: {e}"))
}

fn err(e: impl std::fmt::Display) -> JsError {
    JsError::new(&e.to_string())
}

/// The scopes the embedded module declares, in order — what a page asks
/// its store for before it opens a peer.
#[wasm_bindgen]
pub fn scopes() -> Result<Vec<String>, JsError> {
    let m = load_module().map_err(err)?;
    Ok(m.schema.scopes.iter().map(|s| s.name.clone()).collect())
}

// -- what a scope is kept as -------------------------------------------------
//
// The desktop's `storage.rs` shape, byte for byte: `{ confirmed, cursor,
// pending }` as canonical CBOR — exactly what `Replica::open` takes.

struct Durable {
    confirmed: MemoryStore,
    cursor: Seq,
    pending: Vec<Entry>,
}

fn durable_value(d: &Durable) -> Value {
    Value::record(vec![
        ("confirmed", d.confirmed.store_value()),
        ("cursor", Value::Int(d.cursor)),
        ("pending", Value::List(d.pending.iter().map(entry_value).collect())),
    ])
}

fn durable_of(schema: Schema, bytes: &[u8]) -> Result<Durable, String> {
    let v = canon::decode(bytes).map_err(|e| e.to_string())?;
    let Value::Struct(m) = &v else {
        return Err("a scope is a struct".into());
    };
    let confirmed = MemoryStore::from_value(schema, m.get("confirmed").ok_or("no confirmed store")?);
    let cursor = match m.get("cursor") {
        Some(Value::Int(n)) => *n,
        _ => return Err("no cursor".into()),
    };
    let pending = match m.get("pending") {
        Some(Value::List(es)) => es
            .iter()
            .map(entry_from_value)
            .collect::<Result<Vec<Entry>, _>>()
            .map_err(|e| e.to_string())?,
        _ => return Err("no pending".into()),
    };
    Ok(Durable { confirmed, cursor, pending })
}

// -- the two draws a mutation is allowed --------------------------------------

fn now_ms() -> i64 {
    js_sys::Date::now() as i64
}

fn fresh_id() -> Result<Id, JsError> {
    let mut id = [0u8; 16];
    getrandom::getrandom(&mut id).map_err(|e| err(format!("no randomness: {e}")))?;
    Ok(id)
}

fn autos_for(f: &Function) -> Result<Args, JsError> {
    let mut out = Args::new();
    for (name, auto) in &f.autos {
        let v = match auto {
            Auto::NewId(_) => Value::Id(fresh_id()?),
            Auto::Now => Value::Int(now_ms()),
        };
        out.insert(name.clone(), v);
    }
    Ok(out)
}

// -- JSON <-> Value -----------------------------------------------------------
//
// Inbound is typed by the function's declared arguments, because a JSON
// string is a text, an id, an enum or hex bytes and only the type says
// which. Outbound is by shape: an int is a number while a double can hold
// it and a string after, an id is its 8-4-4-4-12 text, bytes are hex.

fn value_of(ty: &Ty, j: &Json) -> Result<Value, String> {
    Ok(match (ty, j) {
        (Ty::Option(_), Json::Null) => Value::Null,
        (Ty::Option(t), _) => value_of(t, j)?,
        (Ty::Bool, Json::Bool(b)) => Value::Bool(*b),
        (Ty::Int, Json::Number(n)) => Value::Int(n.as_i64().ok_or_else(|| format!("{n} is not an integer"))?),
        (Ty::Int, Json::String(s)) => Value::Int(s.parse::<i64>().map_err(|_| format!("{s:?} is not an integer"))?),
        (Ty::Text, Json::String(s)) => Value::Text(s.clone()),
        (Ty::Bytes, Json::String(s)) => Value::Bytes(decode_hex(s).ok_or_else(|| format!("{s:?} is not hex"))?),
        (Ty::Id(t), Json::String(s)) => Value::Id(id_of_text(s).ok_or_else(|| format!("{s:?} is not an id of {t}"))?),
        (Ty::Enum(vs), Json::String(s)) if vs.contains(s) => Value::Text(s.clone()),
        (Ty::Enum(vs), Json::String(s)) => return Err(format!("{s:?} is none of {vs:?}")),
        (Ty::List(t), Json::Array(xs)) => Value::List(xs.iter().map(|x| value_of(t, x)).collect::<Result<_, _>>()?),
        (Ty::Struct(fields), Json::Object(o)) => {
            let mut m = BTreeMap::new();
            for (name, t) in fields {
                let v = match o.get(name) {
                    Some(x) => value_of(t, x)?,
                    None if matches!(t, Ty::Option(_)) => Value::Null,
                    None => return Err(format!("missing field {name}")),
                };
                m.insert(name.clone(), v);
            }
            Value::Struct(m)
        }
        (t, j) => return Err(format!("expected {t:?}, got {j}")),
    })
}

fn json_of(v: &Value) -> Json {
    match v {
        Value::Null => Json::Null,
        Value::Bool(b) => Json::Bool(*b),
        Value::Int(n) if n.abs() <= SAFE_INT => json!(n),
        Value::Int(n) => Json::String(n.to_string()),
        Value::Text(t) => Json::String(t.clone()),
        Value::Bytes(b) => Json::String(hex(b)),
        Value::Id(i) => Json::String(text_of_id(i)),
        Value::List(xs) => Json::Array(xs.iter().map(json_of).collect()),
        Value::Struct(m) => Json::Object(m.iter().map(|(k, v)| (k.clone(), json_of(v))).collect()),
    }
}

/// The arguments of a call from its JSON object, each at the type the
/// function declares. An empty string is no arguments.
fn args_of(f: &Function, input: &str) -> Result<Args, String> {
    let parsed: Json = if input.trim().is_empty() {
        Json::Object(JsonMap::new())
    } else {
        serde_json::from_str(input).map_err(|e| format!("input is not JSON: {e}"))?
    };
    let Json::Object(o) = &parsed else {
        return Err("input is a JSON object".into());
    };
    let mut args = Args::new();
    for (name, ty) in &f.args {
        let v = match o.get(name) {
            Some(x) => value_of(ty, x).map_err(|e| format!("{}: {name}: {e}", f.name))?,
            None if matches!(ty, Ty::Option(_)) => Value::Null,
            None => return Err(format!("{}: missing argument {name}", f.name)),
        };
        args.insert(name.clone(), v);
    }
    Ok(args)
}

fn refusal_text(why: &Refusal) -> String {
    match why {
        Refusal::Refused(s) => s.clone(),
        other => other.to_string(),
    }
}

// -- the peer -------------------------------------------------------------------

/// One replica per scope, and the authority for each when there is no
/// server. Everything below is synchronous; the page owns the socket and
/// the store and calls in.
#[wasm_bindgen]
pub struct Peer {
    module: Module,
    schema: Schema,
    bodies: BTreeMap<FnHash, Closure>,
    client: Client,
    /// One per scope when alone; empty when a server sequences for us.
    authorities: BTreeMap<ScopeName, Authority>,
    ctx: Ctx,
    server: Option<String>,
    /// What each scope was last persisted as: the cursor and the pending ids.
    written: BTreeMap<ScopeName, (Seq, Vec<Id>)>,
    rejections_seen: usize,
    last_refusal: Option<String>,
}

#[wasm_bindgen]
impl Peer {
    /// Open the peer as `user`, against `server` (`ws://…/sync`) or alone
    /// when it is null. `load(scope)` answers with the bytes `persist`
    /// last handed out for that scope, or undefined for a scope never
    /// saved — how the page's IndexedDB reaches a synchronous open.
    pub fn open(user: &str, server: Option<String>, load: &JsFunction) -> Result<Peer, JsError> {
        let module = load_module().map_err(err)?;
        let schema = module.schema.clone();
        let bodies = closures(&module);
        let ctx = Ctx::new(user, SESSION);
        let mut client = Client::open(schema.clone(), Some(user.to_string()));
        let mut authorities = BTreeMap::new();
        let mut written = BTreeMap::new();
        for sc in &schema.scopes {
            let saved = load.call1(&JsValue::NULL, &JsValue::from_str(&sc.name)).map_err(|_| err("load threw"))?;
            let d = if saved.is_undefined() || saved.is_null() {
                Durable {
                    confirmed: MemoryStore::empty(schema.clone()),
                    cursor: 0,
                    pending: vec![],
                }
            } else {
                durable_of(schema.clone(), &Uint8Array::new(&saved).to_vec()).map_err(|e| err(format!("{}: {e}", sc.name)))?
            };
            written.insert(sc.name.clone(), (d.cursor, d.pending.iter().map(|e| e.id).collect()));
            if server.is_none() {
                // The authority a peer alone is for its own scope: its log
                // is the confirmed store as a snapshot at the cursor, with
                // nothing above it yet.
                authorities.insert(
                    sc.name.clone(),
                    Authority {
                        scope: sc.name.clone(),
                        schema: schema.clone(),
                        bodies: bodies.clone(),
                        log: Log {
                            base: snapshot_of(d.cursor, d.confirmed.clone()),
                            entries: BTreeMap::new(),
                            ids: BTreeMap::new(),
                        },
                        store: d.confirmed.clone(),
                    },
                );
            }
            client.subscribe(
                Mode::Whole,
                Replica::open(schema.clone(), &sc.name, bodies.clone(), d.confirmed, d.cursor, d.pending),
            );
        }
        let mut peer = Peer {
            module,
            schema,
            bodies,
            client,
            authorities,
            ctx,
            server,
            written,
            rejections_seen: 0,
            last_refusal: None,
        };
        // Alone, nothing stays pending: whatever a previous run left is
        // sequenced now.
        peer.commit_alone();
        Ok(peer)
    }

    /// Author a mutation by name, its arguments as a JSON object. The
    /// verdict: undefined when the entry was accepted (and pushed, if
    /// linked), the refusal's text otherwise. Throws only for a mistake in
    /// the call — an unknown function, an argument of the wrong shape.
    pub fn mutate(&mut self, name: &str, input: &str) -> Result<Option<String>, JsError> {
        let f = self
            .module
            .lookup_function(name)
            .ok_or_else(|| err(format!("the module has no function {name}")))?;
        if f.kind != FnKind::Mutator {
            return Err(err(format!("{name} is not a mutator")));
        }
        let scope = f.scope.clone().ok_or_else(|| err(format!("{name} has no scope")))?;
        let fh = self
            .bodies
            .iter()
            .find(|(_, c)| c.function.name == name)
            .map(|(h, _)| h.clone())
            .ok_or_else(|| err(format!("no closure for {name}")))?;
        let args = args_of(f, input).map_err(err)?;
        let autos = autos_for(f)?;
        let ctx = self.ctx.clone();
        let id = fresh_id()?;
        match self.client.mutate(&scope, id, &ctx, &fh, &autos, &args) {
            Ok(_) => {
                self.commit_alone();
                self.note_rejections();
                Ok(None)
            }
            Err(why) => {
                let text = refusal_text(&why);
                self.last_refusal = Some(text.clone());
                Ok(Some(text))
            }
        }
    }

    /// Run a query by name over the optimistic view of every scope, its
    /// arguments as a JSON object; the result as JSON. A query reads one
    /// scope, but the module's schema spans both and a table's name says
    /// which, so the views are laid together and the query finds its own.
    pub fn query(&self, name: &str, input: &str) -> Result<String, JsError> {
        let f = self
            .module
            .lookup_function(name)
            .ok_or_else(|| err(format!("the module has no function {name}")))?;
        if f.kind != FnKind::Query {
            return Err(err(format!("{name} is not a query")));
        }
        let args = args_of(f, input).map_err(err)?;
        let mut views = self.client.scopes.values().map(|(r, _)| &r.view);
        let store = match views.next() {
            Some(first) => views.fold(first.clone(), |acc, v| acc.merge(v)),
            None => MemoryStore::empty(self.schema.clone()),
        };
        let v = ark::eval::query(&self.module, name, &args, &store).map_err(|e| err(format!("{name}: {e:?}")))?;
        Ok(json_of(&v).to_string())
    }

    // -- the socket's side ----------------------------------------------------

    /// The socket opened: hello for every scope, then everything pending.
    pub fn connected(&mut self) {
        self.client.connected();
    }

    /// The socket closed; what was queued is dropped and said again next time.
    pub fn disconnected(&mut self) {
        self.client.disconnected();
    }

    /// A binary frame from the server: canonical CBOR of a `ServerMsg`.
    pub fn frame(&mut self, bytes: &[u8]) -> Result<(), JsError> {
        let v = canon::decode(bytes).map_err(|e| err(format!("frame: {e}")))?;
        let msg = ServerMsg::from_value(&v).map_err(|e| err(format!("frame: {e}")))?;
        self.client.recv(msg);
        self.note_rejections();
        Ok(())
    }

    /// The frames to send, oldest first, each a `Uint8Array` of canonical
    /// CBOR. Empty while unlinked.
    #[wasm_bindgen(js_name = takeOutgoing)]
    pub fn take_outgoing(&mut self) -> Array {
        self.client
            .take_outgoing()
            .iter()
            .map(|m| Uint8Array::from(canon::encode(&m.to_value()).as_slice()))
            .collect()
    }

    /// Periodic housekeeping, on whatever cadence the page likes. Alone it
    /// sequences anything pending; against a server there is nothing timed
    /// in the engine, and it exists so the page has one place to call.
    pub fn tick(&mut self) {
        self.commit_alone();
        self.note_rejections();
    }

    /// Whether any scope's optimistic view moved since this was last asked.
    /// A rebase rolls a view back and rebuilds it, so the answer is a bit
    /// and the page re-reads, rather than a patch list it could mis-apply.
    #[wasm_bindgen(js_name = takeChanges)]
    pub fn take_changes(&mut self) -> bool {
        let mut moved = false;
        for (r, _) in self.client.scopes.values_mut() {
            match r.take_changes() {
                Changes::Rebuilt => moved = true,
                Changes::Applied(chs) => moved = moved || !chs.is_empty(),
            }
        }
        moved
    }

    /// Every scope whose cursor or pending moved since it was last handed
    /// out, as `[scope, Uint8Array]` pairs for the page to store — what
    /// `open`'s `load` gives back. Empty when nothing moved.
    pub fn persist(&mut self) -> Array {
        let out = Array::new();
        for (name, (r, _)) in &self.client.scopes {
            let now = (r.cursor, r.pending.iter().map(|e| e.id).collect::<Vec<Id>>());
            if self.written.get(name) == Some(&now) {
                continue;
            }
            let d = Durable {
                confirmed: r.confirmed.clone(),
                cursor: r.cursor,
                pending: r.pending.clone(),
            };
            let bytes = canon::encode(&durable_value(&d));
            let pair = Array::new();
            pair.push(&JsValue::from_str(name));
            pair.push(&Uint8Array::from(bytes.as_slice()));
            out.push(&pair);
            self.written.insert(name.clone(), now);
        }
        out
    }

    /// The status line, as JSON: `user`, `server`, `alone`, `linked`,
    /// `denied`, `cursors` (scope → seq), `pending`, `diverged`,
    /// `lastRefusal`, `module` (the module's hash).
    pub fn status(&self) -> String {
        let cursors: JsonMap<String, Json> = self.client.scopes.iter().map(|(s, (r, _))| (s.clone(), json!(r.cursor))).collect();
        json!({
            "user": self.ctx.user,
            "server": self.server,
            "alone": !self.authorities.is_empty(),
            "linked": self.client.linked,
            "denied": self.client.denied,
            "cursors": cursors,
            "pending": self.client.scopes.values().map(|(r, _)| r.pending.len()).sum::<usize>(),
            "diverged": self.client.scopes.values().map(|(r, _)| r.diverged.len()).sum::<usize>(),
            "lastRefusal": self.last_refusal,
            "module": hex(&module_hash(&self.module)),
        })
        .to_string()
    }
}

impl Peer {
    // Alone: sequence everything pending in every scope and take the answers.
    fn commit_alone(&mut self) {
        for (scope, a) in &mut self.authorities {
            if let Some((r, _)) = self.client.scopes.get_mut(scope) {
                local_commit(a, r);
            }
        }
    }

    // A verdict that came back — from the server, or from the authority
    // alone — is the newest refusal to show.
    fn note_rejections(&mut self) {
        let all: Vec<String> = self
            .client
            .scopes
            .values()
            .flat_map(|(r, _)| r.rejections.iter().map(|(_, why)| refusal_text(why)))
            .collect();
        if all.len() > self.rejections_seen {
            self.last_refusal = all.last().cloned();
            self.rejections_seen = all.len();
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_embedded_module_decodes_and_names_harkens_functions() {
        let m = load_module().unwrap();
        for f in [
            "create_playlist",
            "add_to_playlist",
            "remove_from_playlist",
            "library",
            "playlists",
            "playlist_items",
        ] {
            assert!(m.lookup_function(f).is_some(), "no {f}");
        }
        assert_eq!(
            m.schema.scopes.iter().map(|s| s.name.as_str()).collect::<Vec<_>>(),
            ["library", "playlists"]
        );
    }

    #[test]
    fn json_round_trips_by_type() {
        let id = "0123456789abcdef0123456789abcdef";
        let text = format!("{}-{}-{}-{}-{}", &id[..8], &id[8..12], &id[12..16], &id[16..20], &id[20..]);
        let v = value_of(&Ty::Id("track".into()), &Json::String(text.clone())).unwrap();
        assert_eq!(json_of(&v), Json::String(text));
        assert_eq!(value_of(&Ty::Int, &json!(7)).unwrap(), Value::Int(7));
        assert_eq!(value_of(&Ty::Int, &json!("9007199254740993")).unwrap(), Value::Int(9007199254740993));
        assert_eq!(json_of(&Value::Int(9007199254740993)), Json::String("9007199254740993".into()));
        assert_eq!(value_of(&Ty::Option(Box::new(Ty::Text)), &Json::Null).unwrap(), Value::Null);
        assert!(value_of(&Ty::Text, &json!(3)).is_err());
    }
}
